# Generated by Django 5.0.6 on 2025-04-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_phone_no'),
        #('auth', '0014_remove_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
