# Generated by Django 5.0.6 on 2024-09-15 18:12

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='phone_no'),
        ),
    ]
