"""
Django settings for web_transformation project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
#import environ
from pathlib import Path
from os import path
import os
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.contrib.messages import constants as messages
#import ldap
#from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

# Initialize environment variables
#env = environ.Env()
#environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9dwcmhwk*n$71$3rdw1)v@n&79*_7-8)sc0oq(6va(ic6te09p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True 

USE_X_FORWARDED_HOST =True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['enhancex.spin-ng.local',
    '10.34.155.206', 
    '127.0.0.1', 
    'localhost'
 ]

CSRF_TRUSTED_ORIGINS = [
    'http://enhancex.spin-ng.local',
    'http://10.34.155.206:8000', 
    'http://10.34.155.206', 
]

SESSION_COOKIE_DOMAIN = None # Allows IP access without domain restriction
CSRF_COOKIE_DOMAIN = None


SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# Application definition

INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'django_plotly_dash',
    'django.contrib.staticfiles',

    'Fit4',
    'dashboard',
    'reports',

    'crispy_forms',
    'crispy_bootstrap5',
    'multiselectfield',
    'simple_menu',
    
    'widget_tweaks',
    'django.contrib.humanize',
    'bootstrap_datepicker_plus',
    'multiforloop',
    #'django_auth_ldap',

    'django_sso.sso_gateway',
    
    'django_filters',
    'rest_framework',

    'table',
    
    'ckeditor',
    'ckeditor_uploader',
    
    #'django_select2',
    'user_visit',
    
    #'report_builder',
    'chartjs',
    'django_htmx',
    'pdf2pptxsite',
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        # ...
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    'django_htmx.middleware.HtmxMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_visit.middleware.UserVisitMiddleware',
    # ... existing middleware ...
    
    #Comment out these two lines below when you are in development environment
    # This will allow you to see Traceback errors, or you will be sent to 
    # the home page and will not know what happened
    
    #'Fit4.middleware.error_email_middleware.ErrorEmailMiddleware', # Update path as needed
    #'Fit4.middleware.db_error_handler.DatabaseErrorMiddleware',
    'Fit4.middleware.db_error_handler.LogoutAnonymousUserMiddleware', 
    
]

# Authentication Backends
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.RemoteUserBackend',
#     #'django.contrib.auth.backends.ModelBackend',
#     #'account.authentication.EmailAuthBackend',
# ]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # This should be the first if you are using django Authentication. Authentication stopped workin I have to swap them
    #'django_auth_ldap.backend.LDAPBackend',
    # This is required for fallback
]
# LDAP Server Settings
AUTH_LDAP_SERVER_URI = "ldap://phc-s-51006.africa-me.shell.com"   # Replace 'your-ldap-server-url' with actual AD server details
AUTH_LDAP_BIND_DN = "CN=your-ldap-bind-user,OU=Users,DC=your-domain,DC=com" # Replace 'your-ldap-bind-user' with actual AD server details
AUTH_LDAP_BIND_PASSWORD = "your-ldap-bind-password" # Replace 'your-ldap-bind-password' with actual AD server details
# Map LDAP attributes to Django user fields
AUTH_LDAP_USER_ATTR_MAP = {
  "username": "sAMAccountName",
  "first_name": "givenName",
  "last_name": "sn",
  "email": "mail",
}

#AUTH_LDAP_FIND_GROUP_PERMS = True
#AUTH_LDAP_MIRROR_GROUPS = True
# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#   "OU=Users,DC=your-domain,DC=com", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)",
# )


ROOT_URLCONF = 'web_transformation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["Fit4/templates", "account/templates", "dashboard/templates", "MTO/templates" ],
        #'DIRS': [os.path.join(BASE_DIR,'Fit4/templates'), os.path.join(BASE_DIR, 'dashboard/templates'), os.path.join(BASE_DIR, 'MTO/templates')],#add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Fit4.context_processors.global_function',
                'Fit4.context_processors.global_Initiative',
                #'django.core.context_processors.media',
                #'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_transformation.wsgi.application'
ASGI_APPLICATION = 'web_transformation.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "enhancex",
        "USER": "enhancex",
        "PASSWORD": "1qazxsw2@12345",
        "HOST": "PHC-S-08079.spin-ng.local\\INST1",
        "PORT": "51697",
        "OPTIONS": {"driver": "ODBC Driver 17 for SQL Server"},
    },
}


# Django variable. URL for unlogged users. We redirect it to our view.
LOGIN_URL = '/account/login_page'
LOGIN_REDIRECT_URL = '/account/login_page'
#LOGIN_URL = 'login'
#LOGOUT_URL = '127.0.0.1:8000'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

TIME_ZONE = 'Africa/Lagos'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#### Menu System ######
MENU_SELECT_PARENTS = True
MENU_HIDE_EMPTY = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'static'), ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')
#STATIC_ROOT = os.path.join(BASE_DIR, 'dashboard/static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Fit4/media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # In Development environment
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" # In Production environment
EMAIL_HOST = '127.0.0.1'
EMAIL_PORT = 25 #587
EMAIL_USE_TLS = False #True
EMAIL_HOST_USER = 'noreply@raecafrica.com'
# EMAIL_HOST_PASSWORD = '' #'Euaggelisis123'
# EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMINS = [
    ('Isaac Bejide', 'isaac.bejide@raecafrica.com'), 
    #('Isaac Bejide', 'isaac.bejide@spnigeria.com'),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_log_file': {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            # 'level': 'DEBUG',
            # 'class': 'logging.FileHandler',
            # 'filename': '/var/log/enhancex/email.log', # make sure this path exists and is writable
        },
    },
    'loggers': {
        'django.core.mail': {
            'handlers': ['mail_log_file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Session Time Out
SESSION_COOKIE_AGE = 7200 # 120 minutes in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = "default"

# # Use Redis as cache backend (Disable when not on the server)
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1", # DB 1 for Django cache
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }

# region CKEDITOR configurations
#CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
#CKEDITOR_UPLOAD_PATH = "uploads/"
#CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'

# CKEDITOR_CONFIGS = {
#     'awesome_ckeditor': {
#         'toolbar': 'Basic',
#     },
# }

# CKEditor Settings
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js' 
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'basicstyles', 'items': ['Source', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            # {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            # {'name': 'insert', 'items': ['Image', 'Flash', 'Html5video', 'Youtube', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            # '/',
            # {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            # {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            # {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            #{'name': 'about', 'items': ['About']},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'height': 250,
        'width': '100%',
        'removePlugins':'resize',
        'resize_enabled':'false',
        'removePlugins':'elementspath',
        'youtube_responsive':'true',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'allowedContent': True,
        
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}

# CKEDITOR_CONFIGS = {
#     'default':
#         {
#             'toolbar': 'full',
#             'width': 'auto',
#             'extraPlugins': ','.join([
#                 'codesnippet',
#             ]),
#         },
# }



#endregion  CKEDITOR configurations

# The link above contains all settings
BOOTSTRAP_DATEPICKER_PLUS = {
    # Options for all input widgets
    # More options: https://getdatepicker.com/4/Options/
    "options": {
        # "locale": "bn",
        "showClose": True,
        "showClear": True,
        "showTodayButton": True,
        "allowInputToggle": True,
    },
    # You can set date and event hook options using JavaScript, usage in README.
    # You can also set options for specific variant widgets only which overrides above options.
    "variant_options": {
        # "date": {
        #     "format": "MM/DD/YYYY",
        # },
        # "datetime": {
        #     "format": "MM/DD/YYYY HH:mm",
        # },
        "month": {
            "format": "MMMM, YYYY",
        },
    },
    #
    # HTML attributes for widget <input> element
    # "attrs": {
    #     "class": "input",
    # },
    #
    # Override input addon icon classes
    "addon_icon_classes": {
        "month": "bi-calendar-month",
    },
    #
    # HTML template to render the html input
    # example: https://github.com/monim67/django-bootstrap-datepicker-plus/blob/5.0.0/dev/myapp/templates/myapp/custom-input.html
    #
    # "template_name": "your-app/custom-input.html",
    #
    # Advanced: Choose where from static JS/CSS files are served.
    # defaults: https://github.com/monim67/django-bootstrap-datepicker-plus/blob/5.0.0/src/bootstrap_datepicker_plus/settings.py#L16
    # To serve from any other preferred CDN, just update the options below.
    # You can also set them to None if you already have the following resources
    # included into your template.
    #
    # "datetimepicker_js_url": "https://..",
    # "datetimepicker_css_url": "https://..",
    # "momentjs_url": None,  # If you already have momentjs added into your template
    # "bootstrap_icon_css_url": None,  # If you don't need bootstrap icons
    #
    # If you want to serve static files yourself without CDN (from staticfiles) and
    # you know how to serve django static files on production server (DEBUG=False)
    # Then download the js/css files to any of your static directory, update the js/css
    # urls above and set the following option
    #
    # "app_static_url": "bootstrap_datepicker_plus/",
}
