# Generated by Django 5.0.6 on 2025-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboards',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboards',
            name='unique_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
