# Generated by Django 5.0.6 on 2025-02-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboards_description_dashboards_unique_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboards',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='dashboards',
            old_name='dashboardName',
            new_name='name',
        ),
    ]
