# Generated by Django 5.0.6 on 2025-02-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboards_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
