# Generated by Django 5.0.6 on 2025-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_dashboards_description_alter_dashboards_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
