# Generated by Django 5.0.6 on 2025-02-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dashboards_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboards',
            options={'ordering': ('-date_updated',)},
        ),
    ]
