# Generated by Django 5.0.6 on 2025-03-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_dashboards_options'),
        ('reports', '0023_alter_savedfilter_filter_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboards',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SavedFilter_rel_set', to='reports.savedfilter'),
        ),
    ]
