# Generated by Django 5.0.6 on 2025-03-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboards_filter'),
        ('reports', '0025_remove_initiative_report_filter_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='filter',
        ),
        migrations.AddField(
            model_name='dashboards',
            name='filter',
            field=models.ManyToManyField(blank=True, related_name='SavedFilter_rel_set', to='reports.savedfilter'),
        ),
    ]
