# Generated by Django 5.0.6 on 2025-03-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_dashboards_filter_dashboards_filter'),
        ('reports', '0025_remove_initiative_report_filter_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='filter',
        ),
        migrations.AddField(
            model_name='dashboards',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SavedFilter_rel_set', to='reports.savedfilter'),
        ),
    ]
