# Generated by Django 5.0.6 on 2025-06-21 20:49

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0141_alter_workstream_options'),
        ('dashboard', '0009_remove_dashboards_filter_dashboards_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_weekly_recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('recognition', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('report_week', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='opex_weekly_recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('recognition', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('report_week', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='capex_target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('YYear', models.CharField(blank=True, max_length=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capex_target_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='commercial_target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('YYear', models.CharField(blank=True, max_length=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_target_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='delivery_target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('YYear', models.CharField(blank=True, max_length=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_target_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='delivery_weekly_Initiative_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('initiative_name', models.CharField(max_length=80, verbose_name='initiative name')),
                ('initiative_id', models.CharField(max_length=15)),
                ('Yearly_Planned_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Yearly_Forecast_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Yearly_Actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Planned_Date', models.DateField(blank=True, db_index=True, null=True)),
                ('L0_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L1_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L2_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L3_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L4_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L5_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('HashTag', models.TextField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('Date_Downloaded', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_week', models.IntegerField()),
                ('Plan_Relevance', models.ManyToManyField(blank=True, related_name='del_report_planrelevance', to='Fit4.planrelevance')),
                ('SavingType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_report_SavingsType', to='Fit4.savingstype')),
                ('Workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_report_workstream', to='Fit4.workstream')),
                ('actual_Lgate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_report_Actual_LGate', to='Fit4.actual_l_gate')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_report_initiative_owner', to=settings.AUTH_USER_MODEL)),
                ('benefittype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_report_benefittype', to='Fit4.benefittype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_created_by', to=settings.AUTH_USER_MODEL)),
                ('functions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_report_Function', to='Fit4.functions')),
                ('overall_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_report_overall_status', to='Fit4.overall_status')),
                ('workstreamlead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_report_wslead', to=settings.AUTH_USER_MODEL)),
                ('workstreamsponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_report_wssponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='opex_target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('YYear', models.CharField(blank=True, max_length=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opex_target_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='opex_weekly_Initiative_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('initiative_name', models.CharField(max_length=80, verbose_name='initiative name')),
                ('initiative_id', models.CharField(max_length=15)),
                ('Yearly_Planned_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Yearly_Forecast_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Yearly_Actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Planned_Date', models.DateField(blank=True, db_index=True, null=True)),
                ('L0_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L1_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L2_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L3_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L4_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('L5_Completion_Date_Planned', models.DateField(blank=True, db_index=True, null=True)),
                ('HashTag', models.TextField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('Date_Downloaded', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_week', models.IntegerField()),
                ('Plan_Relevance', models.ManyToManyField(blank=True, related_name='report_planrelevance', to='Fit4.planrelevance')),
                ('SavingType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_SavingsType', to='Fit4.savingstype')),
                ('Workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_workstream', to='Fit4.workstream')),
                ('actual_Lgate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_Actual_LGate', to='Fit4.actual_l_gate')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_initiative_owner', to=settings.AUTH_USER_MODEL)),
                ('benefittype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_benefittype', to='Fit4.benefittype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opex_created_by', to=settings.AUTH_USER_MODEL)),
                ('functions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_Function', to='Fit4.functions')),
                ('overall_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_overall_status', to='Fit4.overall_status')),
                ('workstreamlead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_wslead', to=settings.AUTH_USER_MODEL)),
                ('workstreamsponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_wssponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
