# Generated by Django 5.0.6 on 2025-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delivery_weekly_recognition_opex_weekly_recognition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_weekly_initiative_report',
            name='report_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opex_weekly_initiative_report',
            name='report_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
