# Generated by Django 5.0.6 on 2025-06-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_delivery_weekly_recognition_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_weekly_initiative_report',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opex_weekly_initiative_report',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
