# Generated by Django 5.0.6 on 2025-07-04 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_delivery_weekly_initiative_report_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='weekly_commitment_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('functions', models.CharField(max_length=80, verbose_name='functions')),
                ('initiative', models.CharField(max_length=150, verbose_name='initiative')),
                ('commitments', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('date_downloaded', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('report_week', models.IntegerField()),
                ('report_year', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
