# Generated by Django 5.0.6 on 2025-01-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-report_name',)},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='report_name',
        ),
    ]
