# Generated by Django 5.0.6 on 2025-01-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_options_rename_name_report_report_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_name',
            new_name='name',
        ),
    ]
