# Generated by Django 5.0.6 on 2025-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_data',
            name='filters',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
