# Generated by Django 5.0.6 on 2025-01-29 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_data_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='report_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnsNames', models.CharField(max_length=120)),
                ('filters', models.CharField(blank=True, max_length=120, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_header_set', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_header_modified', to=settings.AUTH_USER_MODEL)),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_header', to='reports.report')),
            ],
            options={
                'ordering': ('-columnsNames',),
            },
        ),
        migrations.DeleteModel(
            name='report_data',
        ),
    ]
