# Generated by Django 5.0.6 on 2025-01-29 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_report_header_delete_report_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_header',
            name='filters',
        ),
        migrations.CreateModel(
            name='report_filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.CharField(blank=True, max_length=120, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_filters_set', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_filters_modified', to=settings.AUTH_USER_MODEL)),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_filters', to='reports.report')),
            ],
            options={
                'ordering': ('-filters',),
            },
        ),
    ]
