# Generated by Django 5.0.6 on 2025-02-04 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_report_header_filters_report_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='initiative_report_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkStreamName', models.TextField(blank=True, null=True)),
                ('overall_status', models.TextField(blank=True, null=True)),
                ('discipline', models.TextField(blank=True, null=True)),
                ('Function', models.TextField(blank=True, null=True)),
                ('SavingType', models.TextField(blank=True, null=True)),
                ('workStreamSponsor', models.TextField(blank=True, null=True)),
                ('workStreamLead', models.TextField(blank=True, null=True)),
                ('financeSponsor', models.TextField(blank=True, null=True)),
                ('initiativeSponsor', models.TextField(blank=True, null=True)),
                ('Plan_Relevance', models.TextField(blank=True, null=True)),
                ('Approval_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('HashTag', models.TextField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('YYear', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_report_owner', to=settings.AUTH_USER_MODEL)),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_report_header', to='reports.report')),
            ],
        ),
        migrations.DeleteModel(
            name='report_filters',
        ),
    ]
