# Generated by Django 5.0.6 on 2025-02-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_initiative_report_filter_delete_report_filters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative_report_filter',
            old_name='reporting',
            new_name='report_id',
        ),
    ]
