# Generated by Django 5.0.6 on 2025-02-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_rename_reporting_initiative_report_filter_report_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative_report_filter',
            old_name='report_id',
            new_name='iReport',
        ),
    ]
