# Generated by Django 5.0.6 on 2025-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_report_approval_status_report_function_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='WorkStreamName',
            new_name='WorkStream',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Approval_Status',
        ),
        migrations.AddField(
            model_name='report',
            name='discFilters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='funcFilters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='htFilters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='osFilters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='psFilters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='stFilters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='wsFilters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
