# Generated by Django 5.0.6 on 2025-02-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_rename_workstreamname_report_workstream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='yearFilter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
