# Generated by Django 5.0.6 on 2025-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_report_yearfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Filter_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-filter_name',),
            },
        ),
    ]
