# Generated by Django 5.0.6 on 2025-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_report_filter_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_filter_parameters',
            name='filter_lookup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
