# Generated by Django 5.0.6 on 2025-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_alter_savedfilter_filter_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='filter_params',
            field=models.JSONField(),
        ),
    ]
