# Generated by Django 5.0.6 on 2025-03-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_alter_savedfilter_filter_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfilter',
            name='filter_params2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
