# Generated by Django 5.0.6 on 2025-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_savedfilter_filter_params2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative_report_filter',
            name='author',
        ),
        migrations.RemoveField(
            model_name='initiative_report_filter',
            name='iReport',
        ),
        migrations.DeleteModel(
            name='Report_Filter_parameters',
        ),
        migrations.RemoveField(
            model_name='report_header',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='report_header',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='report_header',
            name='reporting',
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='initiative_report_filter',
        ),
        migrations.DeleteModel(
            name='report_header',
        ),
    ]
