# Generated by Django 5.0.6 on 2025-06-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_remove_initiative_report_filter_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedfilter',
            options={'ordering': ('-date_created',)},
        ),
    ]
