# Generated by Django 5.0.6 on 2024-09-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level1', models.CharField(max_length=250)),
                ('Cost_filter', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('PT_filter', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Function_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstream_owner', to=settings.AUTH_USER_MODEL)),
                ('Level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_sponsor_set', to=settings.AUTH_USER_MODEL)),
                ('Level3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_lead_set', to=settings.AUTH_USER_MODEL)),
                ('Level4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_finance_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstreamname', models.CharField(max_length=250)),
                ('workstreamtarget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('workstreamambition', models.DecimalField(decimal_places=2, max_digits=20)),
                ('workstreamdescription', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_workstream_owner', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_created_set', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_modified_set', to=settings.AUTH_USER_MODEL)),
                ('user_financesponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workstream_finance', to=settings.AUTH_USER_MODEL)),
                ('user_workstreamlead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workstream_wslead', to=settings.AUTH_USER_MODEL)),
                ('user_workstreamsponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workstream_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-workstreamname',),
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_id', models.CharField(max_length=10)),
                ('initiative_name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True, blank=True) ),
                ('problem_statement', models.TextField(null=True, blank=True) ),
                ('overallstatuscommentary', models.TextField(null=True, blank=True) ),
                ('Yearly_Planned_Value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Yearly_Forecast_Value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Yearly_Actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Planned_Date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('L1_Completion_Date_Planned', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('L2_Completion_Date_Planned', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('L3_Completion_Date_Planned', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('L4_Completion_Date_Planned', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('L5_Completion_Date_Planned', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('Actual_L_Gate', models.CharField(blank=True, max_length=5, null=True)),
                ('Approval_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('HashTag', models.CharField(blank=True, max_length=255, null=True)),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('new entry', 'New Entry'), ('needs attention', 'Needs attention'), ('on track', 'On track'), ('on hold', 'On hold'), ('defer', 'Defer'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('overall_status', models.CharField(blank=True, choices=[('new entry', 'New Entry'), ('needs attention', 'Needs attention'), ('on track', 'On track'), ('on hold', 'On hold'), ('defer', 'Defer'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('plan_relavance', models.CharField(blank=True, choices=[('new entry', 'New Entry'), ('needs attention', 'Needs attention'), ('on track', 'On track'), ('on hold', 'On hold'), ('defer', 'Defer'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('phase', models.CharField(blank=True, choices=[('new entry', 'New Entry'), ('needs attention', 'Needs attention'), ('on track', 'On track'), ('on hold', 'On hold'), ('defer', 'Defer'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('Function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Function', to='Fit4.functions')),
                ('financesponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_finance', to=settings.AUTH_USER_MODEL)),
                ('initiative_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_owner', to=settings.AUTH_USER_MODEL)),
                ('workstreamlead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_wslead', to=settings.AUTH_USER_MODEL)),
                ('workstreamsponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_sponsor', to=settings.AUTH_USER_MODEL)),
                ('Plan_Relevance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_planrelevance', to='Fit4.planrelevance')),
                ('SavingType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_SavingsType', to='Fit4.savingstype')),
                ('Workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_workstream', to='Fit4.workstream')),
            ],
            options={
                'ordering': ('-initiative_id',),
            },
        ),
    ]
