# Generated by Django 5.0.6 on 2024-09-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative',
            old_name='initiative_owner',
            new_name='author',
        ),
    ]
