# Generated by Django 5.0.6 on 2024-09-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0002_rename_initiative_owner_initiative_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='initiative_name',
            field=models.CharField(max_length=200, verbose_name='initiative name'),
        ),
    ]
