# Generated by Django 5.0.6 on 2024-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0003_alter_initiative_initiative_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pages', models.IntegerField(default=0)),
            ],
        ),
    ]
