# Generated by Django 5.0.6 on 2024-09-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0004_paginating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functions',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='overallstatuscommentary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planrelevance',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='savingstype',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
