# Generated by Django 5.0.6 on 2024-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0005_alter_functions_title_alter_initiative_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='HashTag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
