# Generated by Django 5.0.6 on 2024-09-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0006_alter_initiative_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='DocumentLink',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='SharepointUrl',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
