# Generated by Django 5.0.6 on 2024-09-15 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0007_initiative_documentlink_initiative_sharepointurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('LTS', 'Long Term Solution'), ('IM', 'Interim Mitigation')], max_length=20, null=True)),
                ('complete_by_phase', models.CharField(blank=True, choices=[('L0', 'L0 Idea'), ('L1', 'L1 Identify'), ('L2', 'L2 Validate'), ('L3', 'L3 Plan'), ('L4', 'L4 Implement'), ('L5', 'L5 Track'), ('L6', 'L5 Completed')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('complemetary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'Open'), ('1', 'In Progress'), ('2', 'Completed'), ('3', 'Cancelled'), ('4', 'Needs Attention'), ('5', 'On Hold')], max_length=20, null=True)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_assignedto', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_created_by', to=settings.AUTH_USER_MODEL)),
                ('initiativeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_actions', to='Fit4.initiative')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcetimeallocation', models.CharField(max_length=200)),
                ('discipline', models.CharField(max_length=200)),
                ('initiativeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_teammember', to='Fit4.initiative')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_teammember', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
