# Generated by Django 5.0.6 on 2024-09-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0008_actions_teammembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='plan_relavance',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='status',
        ),
    ]
