# Generated by Django 5.0.6 on 2024-09-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0009_remove_initiative_plan_relavance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_L_Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LGate', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='Actual_L_Gate',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='phase',
            field=models.CharField(blank=True, choices=[('L0', 'L0 Idea'), ('L1', 'L1 Identify'), ('L2', 'L2 Validate'), ('L3', 'L3 Plan'), ('L4', 'L4 Implement'), ('L5', 'L5 Track'), ('L6', 'L5 Completed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='actual_Lgate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Actual_LGate', to='Fit4.actual_l_gate'),
        ),
    ]
