# Generated by Django 5.0.6 on 2024-09-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0010_actual_l_gate_remove_initiative_actual_l_gate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual_l_gate',
            name='LGate',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
