# Generated by Django 5.0.6 on 2024-09-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0011_alter_actual_l_gate_lgate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnabledBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabledby', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='enabledby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_enabledby', to='Fit4.enabledby'),
        ),
    ]
