# Generated by Django 5.0.6 on 2024-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0012_enabledby_initiative_enabledby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='Plan_Relevance',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='enabledby',
        ),
        migrations.AddField(
            model_name='initiative',
            name='Plan_Relevance',
            field=models.ManyToManyField(blank=True, null=True, related_name='initiative_planrelevance', to='Fit4.planrelevance'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='enabledby',
            field=models.ManyToManyField(blank=True, null=True, related_name='initiative_enabledby', to='Fit4.enabledby'),
        ),
    ]
