# Generated by Django 5.0.6 on 2024-09-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0013_remove_initiative_plan_relevance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='Plan_Relevance',
            field=models.ManyToManyField(blank=True, related_name='initiative_planrelevance', to='Fit4.planrelevance'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='enabledby',
            field=models.ManyToManyField(blank=True, related_name='initiative_enabledby', to='Fit4.enabledby'),
        ),
    ]
