# Generated by Django 5.0.6 on 2024-09-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0014_alter_initiative_plan_relevance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='L1_Completion_Date_Planned',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='L2_Completion_Date_Planned',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='L3_Completion_Date_Planned',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='L4_Completion_Date_Planned',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='L5_Completion_Date_Planned',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='Planned_Date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
