# Generated by Django 5.0.6 on 2024-09-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0015_alter_initiative_l1_completion_date_planned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='L1_Completion_Date_Actual',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='L2_Completion_Date_Actual',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='L3_Completion_Date_Actual',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='L4_Completion_Date_Actual',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='L5_Completion_Date_Actual',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
