# Generated by Django 5.0.6 on 2024-09-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0017_discipline_remove_initiative_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, choices=[('L0', 'Recurring'), ('L1', 'One-Off')], max_length=20, null=True)),
                ('Jan_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Feb_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Mar_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Apr_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('May_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jun_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jul_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Aug_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Sep_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Oct_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Nov_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Dec_Plan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jan_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Feb_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Mar_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Apr_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('May_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jun_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jul_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Aug_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Sep_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Oct_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Nov_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Dec_Forecast', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jan_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Feb_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Mar_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Apr_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('May_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jun_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Jul_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Aug_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Sep_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Oct_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Nov_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Dec_Actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('benefittype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_benefittype', to='Fit4.benefittype')),
                ('initiativeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_initiative_impact', to='Fit4.initiative')),
            ],
        ),
    ]
