# Generated by Django 5.0.6 on 2024-09-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0020_alter_initiativeimpact_apr_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeimpact',
            name='YYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
