# Generated by Django 5.0.6 on 2024-09-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0021_initiativeimpact_yyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeimpact',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency'),
        ),
    ]
