# Generated by Django 5.0.6 on 2024-09-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0022_initiativeimpact_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeimpact',
            name='currency',
            field=models.CharField(blank=True, choices=[('1', 'US Dollar'), ('2', 'Nigerian Naira'), ('3', 'British Pound'), ('4', 'Euro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='frequency',
            field=models.CharField(blank=True, choices=[('0', 'Recurring'), ('1', 'One-Off')], max_length=20, null=True),
        ),
    ]
