# Generated by Django 5.0.6 on 2024-09-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0023_alter_initiativeimpact_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='mark_as_confidential',
            field=models.BooleanField(default=False),
        ),
    ]
