# Generated by Django 5.0.6 on 2024-09-16 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0024_initiative_mark_as_confidential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='actual_Lgate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Actual_LGate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='overall_status',
            field=models.CharField(choices=[('new entry', 'New Entry'), ('needs attention', 'Needs attention'), ('on track', 'On track'), ('on hold', 'On hold'), ('defer', 'Defer'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
