# Generated by Django 5.0.6 on 2024-09-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0025_alter_initiative_actual_lgate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='Yearly_Actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='Yearly_Forecast_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='Yearly_Planned_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='mark_as_confidential',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
