# Generated by Django 5.0.6 on 2024-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0026_alter_initiative_yearly_actual_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='mark_as_confidential',
            field=models.BooleanField(default=False),
        ),
    ]
