# Generated by Django 5.0.6 on 2024-09-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0027_alter_initiative_mark_as_confidential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='initiative_name',
            field=models.CharField(max_length=80, verbose_name='initiative name'),
        ),
    ]
