# Generated by Django 5.0.6 on 2024-09-18 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0028_alter_initiative_initiative_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='initiativesponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_sponsor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='workstreamsponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_wssponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
