# Generated by Django 5.0.6 on 2024-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0029_initiative_initiativesponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='L0_Completion_Date_Actual',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='L0_Completion_Date_Planned',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
