# Generated by Django 5.0.6 on 2024-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0030_initiative_l0_completion_date_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstream',
            name='workstreamambition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='workstreamdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='workstreamtarget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
