# Generated by Django 5.0.6 on 2024-09-22 15:45

import Fit4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0031_alter_workstream_workstreamambition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeimpact',
            name='YYear',
            field=models.CharField(blank=True, choices=Fit4.models.get_years, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='frequency',
            field=models.CharField(blank=True, choices=[('1', 'Recurring'), ('2', 'One-Off')], max_length=20, null=True),
        ),
    ]
