# Generated by Django 5.0.6 on 2024-09-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0032_alter_initiativeimpact_yyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiativeimpact',
            old_name='frequency',
            new_name='frequencies',
        ),
    ]
