# Generated by Django 5.0.6 on 2024-09-22 19:30

import Fit4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0033_rename_frequency_initiativeimpact_frequencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeimpact',
            name='YYear',
            field=models.IntegerField(blank=True, choices=Fit4.models.get_years, max_length=4, null=True),
        ),
    ]
