# Generated by Django 5.0.6 on 2024-09-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0035_alter_initiativeimpact_yyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title')),
            ],
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_currency', to='Fit4.currency'),
        ),
    ]
