# Generated by Django 5.0.6 on 2024-09-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0036_currency_alter_initiativeimpact_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
