# Generated by Django 5.0.6 on 2024-09-22 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0037_alter_currency_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
            ],
        ),
        migrations.RemoveField(
            model_name='initiativeimpact',
            name='frequencies',
        ),
        migrations.AddField(
            model_name='initiativeimpact',
            name='frequency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_frequency', to='Fit4.frequency'),
            preserve_default=False,
        ),
    ]
