# Generated by Django 5.0.6 on 2024-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0038_frequency_remove_initiativeimpact_frequencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='action_name',
            field=models.CharField(default=0, max_length=80, verbose_name='action name'),
            preserve_default=False,
        ),
    ]
