# Generated by Django 5.0.6 on 2024-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0039_actions_action_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='complemetary',
        ),
        migrations.AddField(
            model_name='actions',
            name='completion_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
