# Generated by Django 5.0.6 on 2024-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0040_remove_actions_complemetary_actions_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actions',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
