# Generated by Django 5.0.6 on 2024-10-11 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0042_teammembers_created_by_teammembers_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvalStatusVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='approval_status_visual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approvalStatus', to='Fit4.approvalstatusvisual'),
        ),
    ]
