# Generated by Django 5.0.6 on 2024-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0043_approvalstatusvisual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='next_Lgate_Comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
