# Generated by Django 5.0.6 on 2024-10-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0045_initiativefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativefiles',
            name='initiativeFiles',
            field=models.FileField(blank=True, null=True, upload_to='FileUploads/'),
        ),
    ]
