# Generated by Django 5.0.6 on 2024-10-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0049_initiativenotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativenotes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
