# Generated by Django 5.0.6 on 2024-10-14 09:33

#import ckeditor_uploader.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0050_initiativenotes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativenotes',
            name='Notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
