# Generated by Django 5.0.6 on 2024-10-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0051_alter_initiativenotes_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('financesSponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approvals_finance', to=settings.AUTH_USER_MODEL)),
                ('initiativeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_initiative_approvals', to='Fit4.initiative')),
                ('workStreamLead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approvals_lead', to=settings.AUTH_USER_MODEL)),
                ('workStreamSponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approvals_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
