# Generated by Django 5.0.6 on 2024-10-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0052_initiativeapprovals'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapprovals',
            name='LGateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approvals_LGate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='initiativeapprovals',
            name='initiativeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approvals', to='Fit4.initiative'),
        ),
    ]
