# Generated by Django 5.0.6 on 2024-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0053_initiativeapprovals_lgateid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_l_gate',
            name='GateIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
