# Generated by Django 5.0.6 on 2024-10-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0054_actual_l_gate_gateindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiativeapprovals',
            old_name='financesSponsor',
            new_name='financeSponsor',
        ),
    ]
