# Generated by Django 5.0.6 on 2024-10-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0055_rename_financessponsor_initiativeapprovals_financesponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, verbose_name='slug'),
        ),
    ]
