# Generated by Django 5.0.6 on 2024-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0056_initiative_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='YYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
