# Generated by Django 5.0.6 on 2024-10-22 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0057_initiative_yyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeapprovals',
            name='financeSponsor',
        ),
        migrations.RemoveField(
            model_name='initiativeapprovals',
            name='workStreamLead',
        ),
        migrations.RemoveField(
            model_name='initiativeapprovals',
            name='workStreamSponsor',
        ),
        migrations.AddField(
            model_name='initiativeapprovals',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
