# Generated by Django 5.0.6 on 2024-10-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0058_remove_initiativeapprovals_financesponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapprovals',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
