# Generated by Django 5.0.6 on 2025-01-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0059_initiativeapprovals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeimpact',
            name='benefittype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_benefittype', to='Fit4.benefittype'),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_currency', to='Fit4.currency'),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_frequency', to='Fit4.frequency'),
        ),
    ]
