# Generated by Django 5.0.6 on 2025-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0060_alter_initiativeimpact_benefittype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='overall_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
