# Generated by Django 5.0.6 on 2025-02-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0062_alter_initiative_overall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='overall_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_overall_status', to='Fit4.overall_status'),
        ),
    ]
