# Generated by Django 5.0.6 on 2025-02-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0063_alter_initiative_overall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_impact_currency', to='Fit4.currency'),
        ),
    ]
