# Generated by Django 5.0.6 on 2025-02-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0064_initiative_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeimpact',
            name='currency',
        ),
    ]
