# Generated by Django 5.0.6 on 2025-02-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0065_remove_initiativeimpact_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='overall_status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='initiative_overall_status', to='Fit4.overall_status'),
        ),
    ]
