# Generated by Django 5.0.6 on 2025-02-19 13:30

import Fit4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0066_alter_initiative_overall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeimpact',
            name='YYear',
            field=models.IntegerField(blank=True, choices=Fit4.models.get_years, default=2025, null=True),
        ),
    ]
