# Generated by Django 5.0.6 on 2025-02-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0067_alter_initiativeimpact_yyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='recordType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_recordType', to='Fit4.record_type'),
        ),
    ]
