# Generated by Django 5.0.6 on 2025-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0069_infrastructurecategory_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='UOM',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='impactDays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='rated_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
