# Generated by Django 5.0.6 on 2025-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0070_unit_uom_unit_days_unit_impactdays_unit_margin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('prefix', models.CharField(max_length=10)),
            ],
        ),
    ]
