# Generated by Django 5.0.6 on 2025-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0071_controlsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='initiative_id',
            field=models.CharField(max_length=15),
        ),
    ]
