# Generated by Django 5.0.6 on 2025-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0072_alter_initiative_initiative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='YYear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
