# Generated by Django 5.0.6 on 2025-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0073_alter_initiative_yyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='activate_initiative_approvers',
            field=models.BooleanField(default=False),
        ),
    ]
