# Generated by Django 5.0.6 on 2025-03-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0074_initiative_activate_initiative_approvers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula_Level_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Formula_Level_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Formula_Level_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Formula_Level_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='formula_Level_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Formula1', to='Fit4.formula_level_1'),
        ),
        migrations.AddField(
            model_name='formula_level_1',
            name='formula_Level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Formula2', to='Fit4.formula_level_2'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='formula_Level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Formula2', to='Fit4.formula_level_2'),
        ),
        migrations.AddField(
            model_name='formula_level_2',
            name='formula_Level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Formula3', to='Fit4.formula_level_3'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='formula_Level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Formula3', to='Fit4.formula_level_3'),
        ),
        migrations.AddField(
            model_name='formula_level_3',
            name='formula_Level_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Formula4', to='Fit4.formula_level_4'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='formula_Level_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Formula4', to='Fit4.formula_level_4'),
        ),
    ]
