# Generated by Django 5.0.6 on 2025-03-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0075_formula_level_1_formula_level_2_formula_level_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula_level_1',
            name='formula_Level_2',
        ),
        migrations.RemoveField(
            model_name='formula_level_2',
            name='formula_Level_3',
        ),
        migrations.RemoveField(
            model_name='formula_level_3',
            name='formula_Level_4',
        ),
        migrations.AddField(
            model_name='formula_level_2',
            name='formula_Level_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Formula1', to='Fit4.formula_level_1'),
        ),
        migrations.AddField(
            model_name='formula_level_3',
            name='formula_Level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Formula2', to='Fit4.formula_level_2'),
        ),
        migrations.AddField(
            model_name='formula_level_4',
            name='formula_Level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Formula3', to='Fit4.formula_level_3'),
        ),
    ]
