# Generated by Django 5.0.6 on 2025-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0076_remove_formula_level_1_formula_level_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_level_1',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formula_level_2',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formula_level_3',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formula_level_4',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
    ]
