# Generated by Django 5.0.6 on 2025-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0077_alter_formula_level_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
