# Generated by Django 5.0.6 on 2025-03-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0078_actions_commentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='action_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='actions',
            name='complete_by_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_lgate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit4.action_status'),
        ),
    ]
