# Generated by Django 5.0.6 on 2025-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0081_rename_updated_initiative_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='can_be_replicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initiative',
            name='description_of_solution_identified',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='is_carbon_abatement_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initiative',
            name='is_this_a_replicated_initiative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initiative',
            name='learning_and_description_of_work_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='rationale_for_replication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
