# Generated by Django 5.0.6 on 2025-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0083_rename_date_created_actions_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
