# Generated by Django 5.0.6 on 2025-03-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0084_initiative_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative',
            old_name='Function',
            new_name='functions',
        ),
    ]
