# Generated by Django 5.0.6 on 2025-03-09 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0085_rename_function_initiative_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiativeapprovals',
            options={'ordering': ['-Created_Date']},
        ),
        migrations.AddField(
            model_name='initiativeapprovals',
            name='actualApprover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualAprover_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
