# Generated by Django 5.0.6 on 2025-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0086_alter_initiativeapprovals_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapprovals',
            name='rolePlayed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
