# Generated by Django 5.0.6 on 2025-03-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0088_alter_action_type_last_modified_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiativeimpact',
            old_name='initiativeId',
            new_name='initiative',
        ),
    ]
