# Generated by Django 5.0.6 on 2025-03-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0089_rename_initiativeid_initiativeimpact_initiative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='initiativeId',
            new_name='initiative',
        ),
        migrations.RenameField(
            model_name='initiativeapprovals',
            old_name='initiativeId',
            new_name='initiative',
        ),
        migrations.RenameField(
            model_name='initiativefiles',
            old_name='initiativeId',
            new_name='initiative',
        ),
        migrations.RenameField(
            model_name='initiativenotes',
            old_name='initiativeId',
            new_name='initiative',
        ),
        migrations.RenameField(
            model_name='teammembers',
            old_name='initiativeId',
            new_name='initiative',
        ),
    ]
