# Generated by Django 5.0.6 on 2025-03-30 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0090_rename_initiativeid_actions_initiative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_l_gate',
            name='financesponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LGate_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actual_l_gate',
            name='workstreamlead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LGate_wslead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actual_l_gate',
            name='workstreamsponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LGate_sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
