# Generated by Django 5.0.6 on 2025-03-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0091_actual_l_gate_financesponsor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_l_gate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_created_Lgate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actual_l_gate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_modified_Lgate', to=settings.AUTH_USER_MODEL),
        ),
    ]
