# Generated by Django 5.0.6 on 2025-03-31 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0092_actual_l_gate_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_l_gate',
            name='financesponsor',
        ),
        migrations.RemoveField(
            model_name='actual_l_gate',
            name='workstreamlead',
        ),
        migrations.RemoveField(
            model_name='actual_l_gate',
            name='workstreamsponsor',
        ),
        migrations.CreateModel(
            name='PredefinedApprovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_workstream', to='Fit4.workstream')),
                ('actual_Lgate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_Actual_LGate', to='Fit4.actual_l_gate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_created_PredefinedApprovers', to=settings.AUTH_USER_MODEL)),
                ('financesponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_finance', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_modified_PredefinedApprovers', to=settings.AUTH_USER_MODEL)),
                ('workstreamlead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_wslead', to=settings.AUTH_USER_MODEL)),
                ('workstreamsponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
