# Generated by Django 5.0.6 on 2025-04-01 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0093_remove_actual_l_gate_financesponsor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedapprovers',
            name='financesponsor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_finance2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predefinedapprovers',
            name='financesponsor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_finance3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predefinedapprovers',
            name='workstreamlead2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_wslead2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predefinedapprovers',
            name='workstreamlead3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_wslead3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predefinedapprovers',
            name='workstreamsponsor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_sponsor2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predefinedapprovers',
            name='workstreamsponsor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PredefinedApprovers_sponsor3', to=settings.AUTH_USER_MODEL),
        ),
    ]
