# Generated by Django 5.0.6 on 2025-04-01 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0095_alter_workstream_user_financesponsor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstream',
            name='user_financesponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstream_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='user_workstreamlead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstream_wslead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='user_workstreamsponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstream_sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
