# Generated by Django 5.0.6 on 2025-04-01 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0096_alter_workstream_user_financesponsor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Fit4.action_type'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_assignedto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actions',
            name='complete_by_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_lgate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actions',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_actions', to='Fit4.initiative'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actions',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Fit4.action_status'),
        ),
        migrations.AlterField(
            model_name='actual_l_gate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_created_Lgate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actual_l_gate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_modified_Lgate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formula_level_2',
            name='formula_Level_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formula_Formula1', to='Fit4.formula_level_1'),
        ),
        migrations.AlterField(
            model_name='formula_level_3',
            name='formula_Level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formula_Formula2', to='Fit4.formula_level_2'),
        ),
        migrations.AlterField(
            model_name='formula_level_4',
            name='formula_Level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formula_Formula3', to='Fit4.formula_level_3'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='SavingType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_SavingsType', to='Fit4.savingstype'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='Workstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_workstream', to='Fit4.workstream'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='actual_Lgate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Actual_LGate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='approval_status_visual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_approvalStatus', to='Fit4.approvalstatusvisual'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_impact_currency', to='Fit4.currency'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Discipline', to='Fit4.discipline'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='financesponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='formula_Level_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Formula1', to='Fit4.formula_level_1'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='formula_Level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Formula2', to='Fit4.formula_level_2'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='formula_Level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Formula3', to='Fit4.formula_level_3'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='formula_Level_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Formula4', to='Fit4.formula_level_4'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='functions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Function', to='Fit4.functions'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='infrastructureCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Threat_Category', to='Fit4.infrastructurecategory'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='initiativesponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_sponsor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='overall_status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='initiative_overall_status', to='Fit4.overall_status'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='recordType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_recordType', to='Fit4.record_type'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_Unit', to='Fit4.unit'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='workstreamlead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_wslead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='workstreamsponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_wssponsor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativeapprovals',
            name='LGateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_approvals_LGate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='initiativeapprovals',
            name='actualApprover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actualAprover_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativeapprovals',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativeapprovals',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_approvals', to='Fit4.initiative'),
        ),
        migrations.AlterField(
            model_name='initiativefiles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativefiles',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_file', to='Fit4.initiative'),
        ),
        migrations.AlterField(
            model_name='initiativefiles',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='benefittype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_benefittype', to='Fit4.benefittype'),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiative_frequency', to='Fit4.frequency'),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_initiative_impact', to='Fit4.initiative'),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativenotes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiativenotes',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_note', to='Fit4.initiative'),
        ),
        migrations.AlterField(
            model_name='initiativenotes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='Workstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_workstream', to='Fit4.workstream'),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='actual_Lgate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_Actual_LGate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_created_PredefinedApprovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='financesponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='financesponsor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_finance2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='financesponsor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_finance3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_modified_PredefinedApprovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='workstreamlead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_wslead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='workstreamlead2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_wslead2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='workstreamlead3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_wslead3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='workstreamsponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_sponsor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='workstreamsponsor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_sponsor2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predefinedapprovers',
            name='workstreamsponsor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PredefinedApprovers_sponsor3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_teammember', to='Fit4.initiative'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_teammember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_workstream_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_modified_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='user_financesponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workstream_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='user_workstreamlead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workstream_wslead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstream',
            name='user_workstreamsponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workstream_sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
