# Generated by Django 5.0.6 on 2025-04-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0097_alter_actions_action_type_alter_actions_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstream',
            name='SavingType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstream_SavingsType', to='Fit4.savingstype'),
        ),
        migrations.AddField(
            model_name='workstream',
            name='formula_Level_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstream_Formula1', to='Fit4.formula_level_1'),
        ),
        migrations.AddField(
            model_name='workstream',
            name='formula_Level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstream_Formula2', to='Fit4.formula_level_2'),
        ),
        migrations.AddField(
            model_name='workstream',
            name='formula_Level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstream_Formula3', to='Fit4.formula_level_3'),
        ),
        migrations.AddField(
            model_name='workstream',
            name='formula_Level_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstream_Formula4', to='Fit4.formula_level_4'),
        ),
        migrations.AddField(
            model_name='workstream',
            name='functions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workstream_Function', to='Fit4.functions'),
        ),
    ]
