# Generated by Django 5.0.6 on 2025-04-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0098_workstream_savingtype_workstream_formula_level_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstream',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, verbose_name='slug'),
        ),
    ]
