# Generated by Django 5.0.6 on 2025-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0100_alter_actions_action_type_alter_actions_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
