# Generated by Django 5.0.6 on 2025-04-06 20:39

import Fit4.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0102_menuitem_usermenuconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCFMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('actual_volume_multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('forecast_volume_multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('planned_volume_multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fcf_multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('YYear', models.IntegerField(blank=True, choices=Fit4.models.get_years, default=2025, null=True)),
                ('benefittype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcfmultiplier_benefittype', to='Fit4.benefittype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
