# Generated by Django 5.0.6 on 2025-04-07 10:18

#import ckeditor_uploader.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0103_fcfmultiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstream',
            name='workstreamdescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
