# Generated by Django 5.0.6 on 2025-04-07 12:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0104_alter_workstream_workstreamdescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MTOScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('severity', models.CharField(max_length=300)),
                ('people', models.CharField(max_length=300)),
                ('asset', models.CharField(max_length=300)),
                ('environment', models.CharField(max_length=300)),
                ('community', models.CharField(max_length=300)),
                ('A', models.CharField(blank=True, max_length=300, null=True)),
                ('B', models.CharField(blank=True, max_length=300, null=True)),
                ('C', models.CharField(blank=True, max_length=300, null=True)),
                ('D', models.CharField(blank=True, max_length=300, null=True)),
                ('E', models.CharField(blank=True, max_length=300, null=True)),
                ('proactive', models.BooleanField(default=False)),
                ('proactiveType', models.BooleanField(default=False)),
                ('likelyhoodAssetConsequence', models.BooleanField(default=False)),
                ('severityJustification', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('likehoodJustification', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mtoScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTO_created_by', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_MTO', to='Fit4.initiative')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MTO_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
