# Generated by Django 5.0.6 on 2025-04-07 12:58

import ckeditor_uploader.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0105_mtoscoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtoscoring',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='community',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='likehoodJustification',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='likelyhoodAssetConsequence',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='mtoScore',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='people',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='proactive',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='proactiveType',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='severityJustification',
        ),
        migrations.CreateModel(
            name='MTOScoringInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('proactive', models.BooleanField(default=False)),
                ('proactiveType', models.BooleanField(default=False)),
                ('likelyhoodAssetConsequence', models.BooleanField(default=False)),
                ('severityJustification', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('likehoodJustification', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mtoScore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_MTOScoring', to='Fit4.initiative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
