# Generated by Django 5.0.6 on 2025-04-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0106_remove_mtoscoring_asset_remove_mtoscoring_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetConsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProactiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mtoscoringinfo',
            name='assetConsequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_consequence', to='Fit4.assetconsequence'),
        ),
        migrations.AlterField(
            model_name='mtoscoringinfo',
            name='proactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_proactive', to='Fit4.proactivetype'),
        ),
    ]
