# Generated by Django 5.0.6 on 2025-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0107_assetconsequence_proactivetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtoscoring',
            name='A',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='B',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='C',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='D',
        ),
        migrations.RemoveField(
            model_name='mtoscoring',
            name='E',
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='A0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='A1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='A2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='A3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='A4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='A5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='B0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='B1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='B2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='B3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='B4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='B5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='C0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='C1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='C2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='C3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='C4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='C5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='D0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='D1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='D2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='D3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='D4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='D5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='E0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='E1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='E2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='E3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='E4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtoscoring',
            name='E5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
