# Generated by Django 5.0.6 on 2025-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0109_threshold_initiative_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='oldinitiative_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
