# Generated by Django 5.0.6 on 2025-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0110_initiative_oldinitiative_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeimpact',
            name='impactBusinessResult',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='initiativeimpact',
            name='raecShare',
            field=models.CharField(blank=True, default='100%', max_length=100, null=True),
        ),
    ]
