# Generated by Django 5.0.6 on 2025-04-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0111_initiativeimpact_impactbusinessresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
