# Generated by Django 5.0.6 on 2025-04-20 15:44

import Fit4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0112_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativefiles',
            name='initiativeFiles',
            field=models.FileField(blank=True, null=True, upload_to=Fit4.models.initiative_upload_path),
        ),
    ]
