# Generated by Django 5.0.6 on 2025-04-21 10:11

import Fit4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0113_alter_initiativefiles_initiativefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativefiles',
            name='initiativeFiles',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=Fit4.models.initiative_upload_path),
        ),
    ]
