# Generated by Django 5.0.6 on 2025-04-23 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0114_alter_initiativefiles_initiativefiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapprovals',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiativeapprovals',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
