# Generated by Django 5.0.6 on 2025-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0115_initiativeapprovals_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
