# Generated by Django 5.0.6 on 2025-05-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0116_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
