# Generated by Django 5.0.6 on 2025-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0117_alter_initiative_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityConsequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalConsequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HigestImpactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleConsequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryRamBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryRamColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondHigestImpactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondRamBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondRamColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='assetconsequence',
            name='name',
        ),
        migrations.AddField(
            model_name='assetconsequence',
            name='factor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
