# Generated by Django 5.0.6 on 2025-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0118_communityconsequences_environmentalconsequences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatLikelihood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('factor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('RAM', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
