# Generated by Django 5.0.6 on 2025-05-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0119_threatlikelihood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondHigestImpactCategory',
            new_name='ImpactCategory',
        ),
        migrations.RenameModel(
            old_name='SecondRamColor',
            new_name='RamBox',
        ),
        migrations.RenameModel(
            old_name='PrimaryRamBox',
            new_name='RamColor',
        ),
        migrations.DeleteModel(
            name='HigestImpactCategory',
        ),
        migrations.DeleteModel(
            name='PrimaryRamColor',
        ),
        migrations.DeleteModel(
            name='SecondRamBox',
        ),
    ]
