# Generated by Django 5.0.6 on 2025-05-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0120_rename_secondhigestimpactcategory_impactcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='asset_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_AssetConsequence', to='Fit4.assetconsequence'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='calculated_asset_consequences',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='community_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_CommunityConsequences', to='Fit4.communityconsequences'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='environmental_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_EnvironmentalConsequences', to='Fit4.environmentalconsequences'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='highest_impact_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_ImpactCategory', to='Fit4.impactcategory'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='likelihood_asset_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_ThreatLikelihood', to='Fit4.threatlikelihood'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='likelihood_community_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_ThreatLikelihood', to='Fit4.threatlikelihood'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='likelihood_environment_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment_ThreatLikelihood', to='Fit4.threatlikelihood'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='likelihood_people_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_ThreatLikelihood', to='Fit4.threatlikelihood'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='mto_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='people_consequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_PeopleConsequences', to='Fit4.peopleconsequences'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='primary_ram_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_rambox', to='Fit4.rambox'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='primary_ram_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_ramcolor', to='Fit4.rambox'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='second_highest_impact_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_ImpactCategory', to='Fit4.impactcategory'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='second_ram_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_ramBox', to='Fit4.rambox'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='second_ram_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_ramcolor', to='Fit4.ramcolor'),
        ),
    ]
