# Generated by Django 5.0.6 on 2025-05-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0121_initiative_asset_consequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='impact_justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='likelihood_justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
