# Generated by Django 5.0.6 on 2025-05-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0122_initiative_impact_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='proactive_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_ProactiveType', to='Fit4.proactivetype'),
        ),
    ]
