# Generated by Django 5.0.6 on 2025-05-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0123_initiative_proactive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='PotentialNonProductionCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='PotentialProductionCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
