# Generated by Django 5.0.6 on 2025-05-27 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0124_initiative_potentialnonproductioncost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitImpactEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('percent_impact', models.FloatField(blank=True, null=True)),
                ('days', models.FloatField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fit4.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
