# Generated by Django 5.0.6 on 2025-05-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0125_unitimpactentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitimpactentry',
            name='initiative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_units', to='Fit4.initiative'),
            preserve_default=False,
        ),
    ]
