# Generated by Django 5.0.6 on 2025-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0126_unitimpactentry_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitimpactentry',
            name='financial_impact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitimpactentry',
            name='impact_day',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
