# Generated by Django 5.0.6 on 2025-05-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0127_unitimpactentry_financial_impact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTOScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_index', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_mtoscore', to='Fit4.initiative')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_mtoscore', to='Fit4.unit')),
            ],
            options={
                'unique_together': {('cell_index', 'unit', 'initiative')},
            },
        ),
    ]
