# Generated by Django 5.0.6 on 2025-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0128_mtoscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
