# Generated by Django 5.0.6 on 2025-06-03 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0129_unit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='actual_Lgate',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='initiative_Actual_LGate', to='Fit4.actual_l_gate'),
        ),
        migrations.AlterField(
            model_name='initiativeimpact',
            name='YYear',
            field=models.IntegerField(blank=True, choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], default=2025, null=True),
        ),
    ]
