# Generated by Django 5.0.6 on 2025-06-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0130_initiative_is_active_alter_initiative_actual_lgate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtoscore',
            name='value',
        ),
        migrations.CreateModel(
            name='SelectionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('cell_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Fit4.mtoscore')),
            ],
        ),
    ]
