# Generated by Django 5.0.6 on 2025-06-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0131_remove_mtoscore_value_selectionvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectionvalue',
            old_name='cell_selection',
            new_name='MTOScore_selection',
        ),
    ]
