# Generated by Django 5.0.6 on 2025-06-04 00:07

import ckeditor_uploader.fields

#from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0132_rename_cell_selection_selectionvalue_mtoscore_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='overallstatuscommentary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='problem_statement',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
