# Generated by Django 5.0.6 on 2025-06-04 11:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0133_alter_initiative_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='impact_justification',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='likelihood_justification',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
