# Generated by Django 5.0.6 on 2025-06-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0135_assetconsequence2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetConsequence',
            new_name='Severity',
        ),
        migrations.DeleteModel(
            name='AssetConsequence2',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='asset_consequence',
        ),
        migrations.RemoveField(
            model_name='mtoscoringinfo',
            name='assetConsequence',
        ),
    ]
