# Generated by Django 5.0.6 on 2025-06-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0138_initiative_asset_consequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='asset_consequences',
        ),
    ]
