# Generated by Django 5.0.6 on 2025-06-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0139_remove_initiative_asset_consequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='asset_consequences',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
