# Generated by Django 5.0.6 on 2025-06-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0140_initiative_asset_consequences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstream',
            options={'ordering': ('workstreamname',)},
        ),
    ]
