# Generated by Django 5.0.6 on 2025-07-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0141_alter_workstream_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCFCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('renaissance_share', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('capex_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('opex_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('oil_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('domgas_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('export_gas_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
