# Generated by Django 5.0.6 on 2025-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0142_fcfcalculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcfcalculator',
            name='capex_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fcfcalculator',
            name='domgas_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fcfcalculator',
            name='export_gas_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fcfcalculator',
            name='oil_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fcfcalculator',
            name='opex_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fcfcalculator',
            name='renaissance_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
