# Generated by Django 5.0.6 on 2025-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0143_alter_fcfcalculator_capex_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionFCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
