# Generated by Django 5.0.6 on 2025-07-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0144_productionfcf_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcfcalculator',
            old_name='category_name',
            new_name='asset',
        ),
    ]
