# Generated by Django 5.0.6 on 2025-07-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit4', '0145_rename_category_name_fcfcalculator_asset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FCFCalculator',
            new_name='Asset',
        ),
    ]
